// Auth
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNOUT_BEGIN = "SIGNOUT_BEGIN";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";


// Games
export const GET_GAMES_BEGIN = "GET_GAMES_BEGIN";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_ERROR = "GET_GAMES_ERROR";

export const GET_GAME_BEGIN = "GET_GAME_BEGIN";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_ERROR = "GET_GAME_ERROR";
